name: Tests

on:
  pull_request:

jobs:
  lint:
    name: Prettier lint check
    uses: bgd-labs/github-workflows/.github/workflows/foundry-lint-prettier.yml@main
  test:
    name: Foundry build n test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.READ_ONLY_PAT || github.token }}

      - uses: bgd-labs/action-rpc-env@f56d90aa2505822c6c81a9242625551b68b4859f
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Run Foundry setup
        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main
        with:
          FOUNDRY_VERSION: stable

      - name: Run Forge size
        uses: bgd-labs/github-workflows/.github/actions/foundry-size@main

      - name: Run Gas snapshot check
        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
        with:
          FOUNDRY_PROFILE: gas
          FORGE_SNAPSHOT_CHECK: true

      - name: Run Forge tests
        id: test
        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
        with:
          FOUNDRY_PROFILE: pr
